/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package member2;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import member2.dbconnectmem2;
import net.proteanit.sql.DbUtils;
/**
 *
 * @author Savindu Ranasinghe
 */
public class session_main extends javax.swing.JFrame {

     Connection con = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
    
    public session_main() {
        initComponents();
        con = dbconnectmem2.connect(); 
   //table load   
   loadsessionstable();
   //combo boxes load
   lecturecombo();
   modcodecombo();
   modnamecombo();
   groupid();
     locationcombo();  
        }

    private void clearFields(){
    sesid.setText(null);
    Time_Slot.setText(null);
    }
    
     public void loadsessionstable(){
         try{
              String sql = "SELECT * FROM sessions";
     pst = con.prepareStatement(sql);
        rs = pst.executeQuery();
        
        jTable3.setModel(DbUtils.resultSetToTableModel(rs));
         }
         catch(Exception e){
             System.out.println("error");
         }
    }
     
    
    
     private void lecturecombo(){
     
         try {
             String sql = "SELECT * FROM lecturers";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String lecname = rs.getString("lecturers_name");
             
             LecnameCombo.addItem(lecname);
             
             }
             
         } catch (Exception e) {
             
         }
     
     }
     private void modcodecombo(){
         try {
             String sql = "SELECT * FROM modules";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String modcode = rs.getString("Module_code");
             
             ModcodeCombo.addItem(modcode);
             }
             
         } catch (Exception e) {
             
         }
     }
     private void modnamecombo(){
         try {
               String sql = "SELECT * FROM modules";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String modname = rs.getString("Module_name");
             
             ModnameCombo.addItem(modname);
             }
         } catch (Exception e) {
         }
     }
   
     private void groupid(){
         try {
             String sql = "SELECT * FROM studentgroupsre";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String groupid1 = rs.getString("subgroupid");
             
             GroupidCombo.addItem(groupid1);
             }
         } catch (Exception e) {
         }
     }
     
     private void locationcombo(){
     
         try {
             String sql = "SELECT * FROM rooms";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String room = rs.getString("Room");
             
             LocationCombo.addItem(room);
             }
         } catch (Exception e) {
         }
         
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LecnameCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        ModcodeCombo = new javax.swing.JComboBox<>();
        ModnameCombo = new javax.swing.JComboBox<>();
        TagCombo = new javax.swing.JComboBox<>();
        GroupidCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnsessionAdd = new javax.swing.JButton();
        btnsessionUpdate = new javax.swing.JButton();
        btnsessionDelete = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        sesid = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tslot1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LocationCombo = new javax.swing.JComboBox<>();
        DayCombo = new javax.swing.JComboBox<>();
        tslot2 = new javax.swing.JComboBox<>();
        Time_Slot = new javax.swing.JTextField();
        btntime = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LecnameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecnameComboActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable3);

        TagCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture ", "Lab", "Tutorial" }));

        jLabel1.setText("Lecturer 1");

        jLabel2.setText("Module Code");

        jLabel3.setText("Module Name");

        jLabel4.setText("Tag");

        jLabel5.setText("Group ID");

        jLabel6.setText("Location");

        jLabel7.setText("Day");

        btnsessionAdd.setText("Add");
        btnsessionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsessionAddActionPerformed(evt);
            }
        });

        btnsessionUpdate.setText("Update");
        btnsessionUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsessionUpdateActionPerformed(evt);
            }
        });

        btnsessionDelete.setText("Delete");
        btnsessionDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsessionDeleteActionPerformed(evt);
            }
        });

        jLabel8.setText("Session ID");

        sesid.setEditable(false);

        jLabel9.setText("Time Slot");

        tslot1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "8.30", "9.30", "10.30", "11.30", "12.30", "1.30", "2.30", "3.30", "4.30", "5.30" }));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Clear Text Fields");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        DayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        tslot2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "9.30", "10.30", "11.30", "12.30", "1.30", "2.30", "3.30", "4.30", "5.30" }));

        btntime.setLabel("Generate Time Slot");
        btntime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(906, 906, 906))
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tslot1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tslot2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9))
                                .addGap(46, 46, 46)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(sesid)
                                            .addComponent(LecnameCombo, 0, 151, Short.MAX_VALUE)
                                            .addComponent(ModcodeCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ModnameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(TagCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addComponent(GroupidCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(LocationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(DayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btntime, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                        .addComponent(Time_Slot, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(57, 57, 57)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 614, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsessionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsessionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnsessionDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8)
                    .addComponent(sesid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LecnameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ModcodeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ModnameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TagCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(GroupidCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(LocationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(DayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tslot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tslot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnsessionDelete)
                                    .addComponent(btnsessionUpdate)
                                    .addComponent(btnsessionAdd)
                                    .addComponent(jButton2))
                                .addGap(92, 92, 92))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(Time_Slot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btntime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LecnameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecnameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LecnameComboActionPerformed

    private void btnsessionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsessionAddActionPerformed
      // add button 
      String lecname = LecnameCombo.getSelectedItem().toString();
      
      String modcode = ModcodeCombo.getSelectedItem().toString();
      String modname = ModnameCombo.getSelectedItem().toString();
      String tag = TagCombo.getSelectedItem().toString();
      String gid = GroupidCombo.getSelectedItem().toString();
      String location = LocationCombo.getSelectedItem().toString();
      String day = DayCombo.getSelectedItem().toString();
      String tslot = Time_Slot.getText();
      
      //try catch block
        try {
       String sql = "insert into sessions (sid,Lecturer_1,Module_Code,Module_Name,Tag,Group_Id,Location,Day,Time_slot) values ('"+0+"','"+ lecname +"','"+ modcode +"','"+ modname +"','"+tag+"','"+gid+"','"+location+"','"+day+"','"+tslot+"')"; 
       pst = con.prepareStatement(sql);
       pst.execute();
       
       loadsessionstable();
        } catch (Exception e) {
             System.out.println("fail"+e);
        }
     
    }//GEN-LAST:event_btnsessionAddActionPerformed

    private void btnsessionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsessionUpdateActionPerformed
        
         
         int x = JOptionPane.showConfirmDialog(null,"Do you really want to update ?");
       if(x==0){
          
          String sid = sesid.getText();
         String lecname = LecnameCombo.getSelectedItem().toString();
       
      String modcode = ModcodeCombo.getSelectedItem().toString();
      String modname = ModnameCombo.getSelectedItem().toString();
      String tag = TagCombo.getSelectedItem().toString();
      String gid = GroupidCombo.getSelectedItem().toString();
      String location = LocationCombo.getSelectedItem().toString();
      String day = DayCombo.getSelectedItem().toString();
      String tslot = Time_Slot.getText();
       
       String sql = "UPDATE sessions SET Lecturer_1 ='"+lecname+"' ,Module_Code = '"+modcode+"', Module_Name = '"+modname+"',Tag = '"+tag+"',Group_Id='"+gid+"',Location='"+location+"',Day='"+day+"',Time_slot='"+tslot+"' where sid = '"+sid+"' ";
       
       try{
       pst = con.prepareStatement(sql);
       pst.execute();
       
       loadsessionstable();
       }
       catch(Exception e){
           System.out.println("error" + e);
       }
    
       } 
        
    }//GEN-LAST:event_btnsessionUpdateActionPerformed

    private void btnsessionDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsessionDeleteActionPerformed
       
        int x = JOptionPane.showConfirmDialog(null,"Do you really want to delete ?");
        
        if(x==0){
        
            String idx = sesid.getText();
            
            String sql = "DELETE FROM sessions where sid = '"+ idx +"'";
            
            try {
                pst = con.prepareStatement(sql);
                pst.execute();
                 loadsessionstable();
                
                
            } catch (Exception e) {
                
                System.out.println("error"+e);
                
            }
            
            
        }
       
        
    }//GEN-LAST:event_btnsessionDeleteActionPerformed

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
       
         int r = jTable3.getSelectedRow();
       
       //assign variables to pass the values from the table
       String sid = jTable3.getValueAt(r,0).toString();
       String lecname = jTable3.getValueAt(r,1).toString();
       String modcode = jTable3.getValueAt(r,2).toString();
       String modname = jTable3.getValueAt(r,3).toString();
       String tag = jTable3.getValueAt(r,4).toString();
       String gid = jTable3.getValueAt(r,5).toString();
       String location = jTable3.getValueAt(r,6).toString();
       String day = jTable3.getValueAt(r,7).toString();
       String tslot = jTable3.getValueAt(r,8).toString();
       //pass values from table
       sesid.setText(sid);
       LecnameCombo.setSelectedItem(lecname);
       ModcodeCombo.setSelectedItem(modcode);
       ModnameCombo.setSelectedItem(modname);
       TagCombo.setSelectedItem(tag);
       GroupidCombo.setSelectedItem(gid);
       LocationCombo.setSelectedItem(location);
       DayCombo.setSelectedItem(day);
       Time_Slot.setText(tslot);
      
        
    }//GEN-LAST:event_jTable3MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            member2main mod1 = new member2main();
        mod1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
clearFields();      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btntimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntimeActionPerformed
        
        
        String ts = tslot1.getSelectedItem().toString()+"-"+tslot2.getSelectedItem().toString();
        Time_Slot.setText(ts);
        
    }//GEN-LAST:event_btntimeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new session_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DayCombo;
    private javax.swing.JComboBox<String> GroupidCombo;
    private javax.swing.JComboBox<String> LecnameCombo;
    private javax.swing.JComboBox<String> LocationCombo;
    private javax.swing.JComboBox<String> ModcodeCombo;
    private javax.swing.JComboBox<String> ModnameCombo;
    private javax.swing.JComboBox<String> TagCombo;
    private javax.swing.JTextField Time_Slot;
    private javax.swing.JButton btnsessionAdd;
    private javax.swing.JButton btnsessionDelete;
    private javax.swing.JButton btnsessionUpdate;
    private java.awt.Button btntime;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField sesid;
    private javax.swing.JComboBox<String> tslot1;
    private javax.swing.JComboBox<String> tslot2;
    // End of variables declaration//GEN-END:variables
}
