/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package member2;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import member2.dbconnectmem2;
import net.proteanit.sql.DbUtils;
import timetablemanagement.Sessions;
/**
 *
 * @author Savindu Ranasinghe
 */
public class session_main extends javax.swing.JFrame {

     Connection con = null;
     PreparedStatement pst = null;
     ResultSet rs = null;
    
    public session_main() {
        initComponents();
        con = dbconnectmem2.connect(); 
   //table load   
   loadsessionstable();
   //combo boxes load
   lecturecombo();
   modcodecombo();

   groupid();
   locationcombo();  
        }

    
     public void loadsessionstable(){
          {
             int p;
              try {
            
       
        
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            pst = con.prepareStatement("select * from sessionsmain");
           
           
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            p = Rss.getColumnCount();
            
            DefaultTableModel dft = (DefaultTableModel) sessionstable.getModel();
            dft.setRowCount(0);
            
               while(rs.next())
               {
                   Vector v2 = new Vector();
                   
                   for(int q=1; q<=p; q++)
                   {
                       v2.add(rs.getString("id"));
                       v2.add(rs.getString("lecturer"));
                       v2.add(rs.getString("subject"));
                       v2.add(rs.getString("subjectcode"));
                       v2.add(rs.getString("tag"));
                       v2.add(rs.getString("groups"));
                       v2.add(rs.getString("location"));
                       v2.add(rs.getString("day"));
                       v2.add(rs.getString("duration"));
                       v2.add(rs.getString("tag"));
                       
                   }
                   
                   dft.addRow(v2);
               }
               
            
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(Sessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            
            Logger.getLogger(Sessions.class.getName()).log(Level.SEVERE, null, ex);
        }
          }
     }
     
    
    
     private void lecturecombo(){
     
         try {
             String sql = "SELECT * FROM lecturers";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String lecname = rs.getString("lecturers_name");
             
             LecnameCombo.addItem(lecname);
             
             }
             
         } catch (Exception e) {
             
         }
     
     }
     private void modcodecombo(){
         try {
             String sql = "SELECT * FROM modules";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String modcode = rs.getString("Module_code");
             
             ModnameCombo.addItem(modcode);
             }
             
         } catch (Exception e) {
             
         }
     }
   
     private void groupid(){
         try {
             String sql = "SELECT * FROM studentgroupsre";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String groupid1 = rs.getString("subgroupid");
             
             GroupidCombo.addItem(groupid1);
             }
         } catch (Exception e) {
         }
     }
     
     private void locationcombo(){
     
         try {
             String sql = "SELECT * FROM rooms";
             pst = con.prepareStatement(sql);
             rs = pst.executeQuery();
             
             while(rs.next()){
             String room = rs.getString("roomno");
             
             LocationCombo.addItem(room);
             }
         } catch (Exception e) {
         }
         
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LecnameCombo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        sessionstable = new javax.swing.JTable();
        ModnameCombo = new javax.swing.JComboBox<>();
        subjectcombo = new javax.swing.JComboBox<>();
        GroupidCombo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnsessionAdd = new javax.swing.JButton();
        btnsessionUpdate = new javax.swing.JButton();
        btnsessionDelete = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        LocationCombo = new javax.swing.JComboBox<>();
        DayCombo = new javax.swing.JComboBox<>();
        durationcombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        TagCombo1 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LecnameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LecnameComboActionPerformed(evt);
            }
        });

        sessionstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lecturer", "Subject", "Subject Code", "Tag", "Group", "Location", "Day", "Duration"
            }
        ));
        sessionstable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sessionstableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(sessionstable);

        subjectcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture ", "Lab", "Tutorial" }));

        jLabel1.setText("Lecturer ");

        jLabel3.setText("Code");

        jLabel4.setText("Subject");

        jLabel5.setText("Group");

        jLabel6.setText("Location");

        jLabel7.setText("Day");

        btnsessionAdd.setBackground(new java.awt.Color(0, 204, 0));
        btnsessionAdd.setText("Add");
        btnsessionAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsessionAddActionPerformed(evt);
            }
        });

        btnsessionUpdate.setBackground(new java.awt.Color(0, 51, 255));
        btnsessionUpdate.setText("Update");
        btnsessionUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsessionUpdateActionPerformed(evt);
            }
        });

        btnsessionDelete.setBackground(new java.awt.Color(255, 0, 0));
        btnsessionDelete.setText("Delete");
        btnsessionDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsessionDeleteActionPerformed(evt);
            }
        });

        jLabel9.setText("Duration");

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        DayCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday" }));

        durationcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 Hour", "1.5 Hours", "2 Hours", " " }));

        jLabel8.setText("Tag");

        TagCombo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecture ", "Lab", "Tutorial" }));

        jLabel10.setBackground(new java.awt.Color(204, 204, 204));
        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("   Sessions");
        jLabel10.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(LecnameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(jLabel9)))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(durationcombo, 0, 151, Short.MAX_VALUE)
                            .addComponent(GroupidCombo, 0, 151, Short.MAX_VALUE)
                            .addComponent(LocationCombo, 0, 151, Short.MAX_VALUE)
                            .addComponent(DayCombo, 0, 151, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(subjectcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(TagCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ModnameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(btnsessionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 138, Short.MAX_VALUE)
                        .addComponent(btnsessionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(132, 132, 132)
                        .addComponent(btnsessionDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnsessionAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsessionUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsessionDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LecnameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(subjectcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(ModnameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TagCombo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(GroupidCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(LocationCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(DayCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(durationcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LecnameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LecnameComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LecnameComboActionPerformed

    private void btnsessionAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsessionAddActionPerformed
      // add button 
      String lecname = LecnameCombo.getSelectedItem().toString();
      String subject = subjectcombo.getSelectedItem().toString();
      String modcode = ModnameCombo.getSelectedItem().toString();
      String tag = TagCombo1.getSelectedItem().toString();
      String group = GroupidCombo.getSelectedItem().toString();
      String location = LocationCombo.getSelectedItem().toString();
      String day = DayCombo.getSelectedItem().toString();
      String duration = durationcombo.getSelectedItem().toString();
      
      //try catch block
        try {
       String sql = "insert into sessionsmain (id,lecturer,subject,subjectcode,tag,groups,location,day,duration) values ('"+0+"','"+ lecname +"','"+ subject +"','"+ modcode +"','"+tag+"','"+group+"','"+location+"','"+day+"','"+duration+"')"; 
       pst = con.prepareStatement(sql);
       pst.execute();
       
       loadsessionstable();
        } catch (Exception e) {
             System.out.println("fail"+e);
        }
     
    }//GEN-LAST:event_btnsessionAddActionPerformed

    private void btnsessionUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsessionUpdateActionPerformed
        
         
         int x = JOptionPane.showConfirmDialog(null,"Do you really want to update ?");
       if(x==0){
           
       DefaultTableModel dft = (DefaultTableModel) sessionstable.getModel();
       int selectedIndex = sessionstable.getSelectedRow();   
        
      int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString()); 
      String lecname = LecnameCombo.getSelectedItem().toString();
      String subject = subjectcombo.getSelectedItem().toString();
      String modcode = ModnameCombo.getSelectedItem().toString();
      String tag = TagCombo1.getSelectedItem().toString();
      String group = GroupidCombo.getSelectedItem().toString();
      String location = LocationCombo.getSelectedItem().toString();
      String day = DayCombo.getSelectedItem().toString();
      String duration = durationcombo.getSelectedItem().toString();
       
       String sql = "UPDATE sessionsmain SET lecturer ='"+lecname+"' ,subject = '"+subject+"', subjectcode = '"+modcode+"',tag = '"+tag+"',groups='"+group+"',location='"+location+"',day='"+day+"',duration='"+duration+"' where id = '"+id+"' ";
       
       try{
       pst = con.prepareStatement(sql);
       pst.execute();
       
       loadsessionstable();
       }
       catch(Exception e){
           System.out.println("error" + e);
       }
    
       } 
        
    }//GEN-LAST:event_btnsessionUpdateActionPerformed

    private void btnsessionDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsessionDeleteActionPerformed
       
     DefaultTableModel dft = (DefaultTableModel) sessionstable.getModel();
        int selectedIndex = sessionstable.getSelectedRow();

        try {

            int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());

            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure?","Warning",JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
                pst = con.prepareStatement("delete from sessionsmain where id=?");

                pst.setInt(1, id);

            }

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Deleted");
            loadsessionstable();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(Sessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(Sessions.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }//GEN-LAST:event_btnsessionDeleteActionPerformed

    private void sessionstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sessionstableMouseClicked
       
        DefaultTableModel dft = (DefaultTableModel) sessionstable.getModel();
        int selectedIndex = sessionstable.getSelectedRow();
       
        LecnameCombo.setSelectedItem(dft.getValueAt(selectedIndex, 1).toString());
        subjectcombo.setSelectedItem(dft.getValueAt(selectedIndex, 2).toString());
        ModnameCombo.setSelectedItem(dft.getValueAt(selectedIndex, 3).toString());
        TagCombo1.setSelectedItem(dft.getValueAt(selectedIndex, 4).toString());
        GroupidCombo.setSelectedItem(dft.getValueAt(selectedIndex, 5).toString());
        LocationCombo.setSelectedItem(dft.getValueAt(selectedIndex, 6).toString());
        DayCombo.setSelectedItem(dft.getValueAt(selectedIndex, 7).toString());
        durationcombo.setSelectedItem(dft.getValueAt(selectedIndex, 8).toString());
        

        
    }//GEN-LAST:event_sessionstableMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         member2main mod1 = new member2main();
        mod1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LecnameCombo.setSelectedIndex(0);
        subjectcombo.setSelectedIndex(0);
        ModnameCombo.setSelectedIndex(0);
        TagCombo1.setSelectedIndex(0);
        GroupidCombo.setSelectedIndex(0);
        LocationCombo.setSelectedIndex(0);
        DayCombo.setSelectedIndex(0);
        durationcombo.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(session_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new session_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> DayCombo;
    private javax.swing.JComboBox<String> GroupidCombo;
    private javax.swing.JComboBox<String> LecnameCombo;
    private javax.swing.JComboBox<String> LocationCombo;
    private javax.swing.JComboBox<String> ModnameCombo;
    private javax.swing.JComboBox<String> TagCombo1;
    private javax.swing.JButton btnsessionAdd;
    private javax.swing.JButton btnsessionDelete;
    private javax.swing.JButton btnsessionUpdate;
    private javax.swing.JComboBox<String> durationcombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable sessionstable;
    private javax.swing.JComboBox<String> subjectcombo;
    // End of variables declaration//GEN-END:variables
}
