/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


package timetablemanagement;
import DataBase.DBconnection;
import java.awt.Color;
import static java.awt.Color.red;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author Bimsara De Silva
 */
public class AcedemicYearAndSemester extends javax.swing.JFrame {
    
  
    public tableCellAlignment centerAlign = new tableCellAlignment();
  Connection con;
  DefaultTableModel table ;
  String updaterecord = "";
  Statement stmt;



    /**
     * Creates new form AdedemicYearAndSemester
     */
     public void selectRow(){
     jTable1.addMouseListener(new MouseAdapter(){
     public void mousePressed(MouseEvent me) {
     jTable1 = (JTable)me.getSource();
     int row = jTable1.getSelectedRow();       
     updaterecord = (String) jTable1.getValueAt(row, 2);     
            }
     });
    
    }
    
    public void showDetails() throws SQLException{

        TableCellRenderer rendererFromHeader = jTable1.getTableHeader().getDefaultRenderer();
        JLabel headerLabel = (JLabel) rendererFromHeader;
        headerLabel.setHorizontalAlignment(JLabel.CENTER);
        jTable1.getTableHeader().setFont(new Font("TimesNewRoman", Font.PLAIN, 15));     
        jTable1.getColumnModel().getColumn(0).setCellRenderer(centerAlign);
        jTable1.getColumnModel().getColumn(1).setCellRenderer(centerAlign);
        jTable1.getColumnModel().getColumn(2).setCellRenderer(centerAlign);
        
       Statement stmt = null;
       con = new DBconnection().getDB();
       stmt = con.createStatement();
       String sql = "SELECT id,name,year,semester from AcedemicYearAndSemester ORDER BY year";
       
       ResultSet result = stmt.executeQuery(sql);
        table = (DefaultTableModel) jTable1.getModel(); 
        
       Object[] column = new Object[3];
       
       while(result.next()){
             column[0] = result.getInt("name");
             column[1] =  result.getInt("year");
             column[2] =  result.getString("semester");
             table.addRow(column);
             
       }
   
    }
    
    public String getEditableValue(){
    return this.updaterecord;
    }
    
    
     
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        deleteyands = new javax.swing.JButton();
        addyands = new javax.swing.JButton();
        updateyands = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 65)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Adedemic Year & Semester");

        jTable1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Acedemic Year", "Acedemic Semester"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTable1.setRowHeight(25);
        jTable1.setRowMargin(3);
        jTable1.setSelectionBackground(new java.awt.Color(0, 102, 255));
        jScrollPane1.setViewportView(jTable1);

        deleteyands.setBackground(new java.awt.Color(255, 51, 0));
        deleteyands.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        deleteyands.setText("Delete");
        deleteyands.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        deleteyands.setContentAreaFilled(false);
        deleteyands.setOpaque(true);
        deleteyands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteyandsActionPerformed(evt);
            }
        });

        addyands.setBackground(new java.awt.Color(0, 102, 255));
        addyands.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        addyands.setText("Add");
        addyands.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addyands.setContentAreaFilled(false);
        addyands.setOpaque(true);
        addyands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addyandsActionPerformed(evt);
            }
        });

        updateyands.setBackground(new java.awt.Color(0, 204, 51));
        updateyands.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        updateyands.setText("Update");
        updateyands.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateyands.setContentAreaFilled(false);
        updateyands.setOpaque(true);
        updateyands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateyandsActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(deleteyands, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(addyands, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(updateyands, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addyands, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(updateyands, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(deleteyands, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addyands, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateyands, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteyands, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(20, 20, 20))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 731, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void updateyandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateyandsActionPerformed
       if(updaterecord.equals("")){
      JOptionPane.showMessageDialog(this, "No records are selected","Error",JOptionPane.ERROR_MESSAGE);
      }else{
          try {
              new UpdateYearAndSemester(updaterecord).setVisible(true);
              this.setVisible(false);
          } catch (SQLException e) {
              Logger.getLogger(AcedemicYearAndSemester.class.getName()).log(Level.SEVERE, null, e);
          }
      }
    }//GEN-LAST:event_updateyandsActionPerformed

    private void deleteyandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteyandsActionPerformed
       int index = jTable1.getSelectedRow();
       if(index != -1) {
         try{
           
             int a = JOptionPane.showConfirmDialog(this, "Confirm Deletion?");
             if(a==JOptionPane.YES_OPTION)
        {
        int modelIndex = jTable1.convertRowIndexToModel(index);
        DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
        model.removeRow(modelIndex);

        stmt = new DBconnection().getDB().createStatement();
                
        String sql = "DELETE FROM AcedemicYearAndSemester" + " WHERE Name = '"+updaterecord+"'";
        System.out.println(sql);
        stmt.executeUpdate(sql);
     
        JOptionPane.showMessageDialog(this, "Success","Successful",JOptionPane.INFORMATION_MESSAGE);
            }
            }catch(Exception e){
       JOptionPane.showMessageDialog(this, "Couldn't delete record","Error",JOptionPane.ERROR_MESSAGE);
       
       }
    }else{
       
       JOptionPane.showMessageDialog(this, "No lines selected","Error",JOptionPane.ERROR_MESSAGE);
       }
    }//GEN-LAST:event_deleteyandsActionPerformed

    private void addyandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addyandsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addyandsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AcedemicYearAndSemester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AcedemicYearAndSemester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AcedemicYearAndSemester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AcedemicYearAndSemester.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AcedemicYearAndSemester().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addyands;
    private javax.swing.JButton deleteyands;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton updateyands;
    // End of variables declaration//GEN-END:variables
}
