/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagement;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Bimsara De Silva
 */
public class ReviseActiveSessions extends javax.swing.JFrame {

    /**
     * Creates new form ActiveSessions
     */
    public ReviseActiveSessions() {
        initComponents();
        fillcombogroup();
        fillcombotimeslot();
        fillcombosubjects();
        fillcombolocation();
        fillcombolecturer();
        table_update_lecturers();
        table_update_students();
        table_update_location();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lecturer = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        timeslot = new javax.swing.JComboBox<>();
        lecturer2 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        subjecta = new javax.swing.JComboBox<>();
        subjectb = new javax.swing.JComboBox<>();
        subjectc = new javax.swing.JComboBox<>();
        subjectd = new javax.swing.JComboBox<>();
        subjecte = new javax.swing.JComboBox<>();
        subjectf = new javax.swing.JComboBox<>();
        savelecturer = new javax.swing.JButton();
        updatelecturer = new javax.swing.JButton();
        deletelecturer = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        studentg = new javax.swing.JComboBox<>();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        timeslot1 = new javax.swing.JComboBox<>();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        subject3 = new javax.swing.JComboBox<>();
        subject2 = new javax.swing.JComboBox<>();
        subject1 = new javax.swing.JComboBox<>();
        subject6 = new javax.swing.JComboBox<>();
        subject5 = new javax.swing.JComboBox<>();
        subject4 = new javax.swing.JComboBox<>();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        savestudent = new javax.swing.JButton();
        updatestudent = new javax.swing.JButton();
        deletestudent = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        locationcombo = new javax.swing.JComboBox<>();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        timeslot2 = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        subject9 = new javax.swing.JComboBox<>();
        subject8 = new javax.swing.JComboBox<>();
        subject7 = new javax.swing.JComboBox<>();
        subject12 = new javax.swing.JComboBox<>();
        subject11 = new javax.swing.JComboBox<>();
        subject10 = new javax.swing.JComboBox<>();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        savelocation = new javax.swing.JButton();
        updatelocation = new javax.swing.JButton();
        deletelocation = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        clearbutton_cs1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Lecturer ", "Timeslot", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("TimeSlot");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Lecturer");

        timeslot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeslotActionPerformed(evt);
            }
        });

        lecturer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lecturer2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Tuesday");

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Monday");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Wednesday");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Thursday");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Saturday");

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Friday");

        subjecta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectaActionPerformed(evt);
            }
        });

        subjectb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectbActionPerformed(evt);
            }
        });

        subjectc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectcActionPerformed(evt);
            }
        });

        subjectd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectdActionPerformed(evt);
            }
        });

        subjecte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjecteActionPerformed(evt);
            }
        });

        subjectf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectfActionPerformed(evt);
            }
        });

        savelecturer.setBackground(new java.awt.Color(51, 153, 0));
        savelecturer.setForeground(new java.awt.Color(255, 255, 255));
        savelecturer.setText("Save");
        savelecturer.setContentAreaFilled(false);
        savelecturer.setOpaque(true);
        savelecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savelecturerActionPerformed(evt);
            }
        });

        updatelecturer.setBackground(new java.awt.Color(51, 51, 255));
        updatelecturer.setForeground(new java.awt.Color(255, 255, 255));
        updatelecturer.setText("Update");
        updatelecturer.setContentAreaFilled(false);
        updatelecturer.setOpaque(true);
        updatelecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatelecturerActionPerformed(evt);
            }
        });

        deletelecturer.setBackground(new java.awt.Color(255, 0, 0));
        deletelecturer.setForeground(new java.awt.Color(255, 255, 255));
        deletelecturer.setText("Delete");
        deletelecturer.setContentAreaFilled(false);
        deletelecturer.setOpaque(true);
        deletelecturer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelecturerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel15))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeslot, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lecturer2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel17))
                        .addGap(21, 21, 21)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subjectb, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subjecta, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel22))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel20))))
                        .addComponent(jLabel21))
                    .addComponent(subjectc, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subjecte, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectf, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subjectd, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(savelecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(updatelecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(deletelecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(subjecta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(subjectd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel16)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(subjectb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)
                            .addComponent(subjecte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(subjectc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21)
                            .addComponent(subjectf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lecturer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeslot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletelecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savelecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatelecturer, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35))
        );

        Lecturer.addTab("Lecturer", jPanel2);

        studentg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentgActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Student Group");

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("TimeSlot");

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Wednesday");

        timeslot1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeslot1ActionPerformed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Monday");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Tuesday");

        subject3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject3ActionPerformed(evt);
            }
        });

        subject2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject2ActionPerformed(evt);
            }
        });

        subject1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject1ActionPerformed(evt);
            }
        });

        subject6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject6ActionPerformed(evt);
            }
        });

        subject5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject5ActionPerformed(evt);
            }
        });

        subject4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject4ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Thursday");

        jLabel29.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel29.setText("Friday");

        jLabel30.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel30.setText("Saturday");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Student group", "Timeslot", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        savestudent.setBackground(new java.awt.Color(51, 153, 0));
        savestudent.setForeground(new java.awt.Color(255, 255, 255));
        savestudent.setText("Save");
        savestudent.setContentAreaFilled(false);
        savestudent.setOpaque(true);
        savestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savestudentActionPerformed(evt);
            }
        });

        updatestudent.setBackground(new java.awt.Color(51, 51, 255));
        updatestudent.setForeground(new java.awt.Color(255, 255, 255));
        updatestudent.setText("Update");
        updatestudent.setContentAreaFilled(false);
        updatestudent.setOpaque(true);
        updatestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatestudentActionPerformed(evt);
            }
        });

        deletestudent.setBackground(new java.awt.Color(255, 0, 0));
        deletestudent.setForeground(new java.awt.Color(255, 255, 255));
        deletestudent.setText("Delete");
        deletestudent.setContentAreaFilled(false);
        deletestudent.setOpaque(true);
        deletestudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletestudentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel25)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeslot1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(studentg, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27))
                        .addGap(21, 21, 21)))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel29))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel28))))
                        .addComponent(jLabel30))
                    .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(72, 72, 72))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(savestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(updatestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(deletestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(subject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28)
                    .addComponent(subject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel23)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(subject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel29)
                            .addComponent(subject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(subject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30)
                            .addComponent(subject6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(studentg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeslot1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatestudent, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        Lecturer.addTab("Students", jPanel3);

        locationcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                locationcomboActionPerformed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel31.setText("Location");

        jLabel32.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel32.setText("TimeSlot");

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel33.setText("Wednesday");

        timeslot2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeslot2ActionPerformed(evt);
            }
        });

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Monday");

        jLabel35.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel35.setText("Tuesday");

        subject9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject9ActionPerformed(evt);
            }
        });

        subject8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject8ActionPerformed(evt);
            }
        });

        subject7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject7ActionPerformed(evt);
            }
        });

        subject12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject12ActionPerformed(evt);
            }
        });

        subject11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject11ActionPerformed(evt);
            }
        });

        subject10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subject10ActionPerformed(evt);
            }
        });

        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Thursday");

        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Friday");

        jLabel38.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel38.setText("Saturday");

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Location", "Timeslot", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"
            }
        ));
        jTable3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable3MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable3);

        savelocation.setBackground(new java.awt.Color(51, 153, 0));
        savelocation.setForeground(new java.awt.Color(255, 255, 255));
        savelocation.setText("Save");
        savelocation.setContentAreaFilled(false);
        savelocation.setOpaque(true);
        savelocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savelocationActionPerformed(evt);
            }
        });

        updatelocation.setBackground(new java.awt.Color(51, 51, 255));
        updatelocation.setForeground(new java.awt.Color(255, 255, 255));
        updatelocation.setText("Update");
        updatelocation.setContentAreaFilled(false);
        updatelocation.setOpaque(true);
        updatelocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatelocationActionPerformed(evt);
            }
        });

        deletelocation.setBackground(new java.awt.Color(255, 0, 0));
        deletelocation.setForeground(new java.awt.Color(255, 255, 255));
        deletelocation.setText("Delete");
        deletelocation.setContentAreaFilled(false);
        deletelocation.setOpaque(true);
        deletelocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletelocationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel33)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeslot2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(locationcombo, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jLabel35))
                        .addGap(21, 21, 21)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(subject8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(57, 57, 57)
                                    .addComponent(jLabel37))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(55, 55, 55)
                                    .addComponent(jLabel36))))
                        .addComponent(jLabel38))
                    .addComponent(subject9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subject11, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject12, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subject10, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(savelocation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(updatelocation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(deletelocation, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(subject7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36)
                    .addComponent(subject10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel31)
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel35)
                            .addComponent(subject8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37)
                            .addComponent(subject11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(subject9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel38)
                            .addComponent(subject12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationcombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeslot2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletelocation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savelocation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updatelocation, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28))
        );

        Lecturer.addTab("Locations", jPanel1);

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("                      Active Sessions");
        jLabel7.setOpaque(true);

        clearbutton_cs1.setBackground(new java.awt.Color(153, 153, 153));
        clearbutton_cs1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clearbutton_cs1.setText("Back To Main Dashboard");
        clearbutton_cs1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearbutton_cs1.setContentAreaFilled(false);
        clearbutton_cs1.setOpaque(true);
        clearbutton_cs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutton_cs1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Lecturer)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(clearbutton_cs1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clearbutton_cs1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(Lecturer)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    Connection con;
    PreparedStatement pst;
    
         
    
     private void fillcombogroup(){
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            String sql = "select * from studentgroupsre";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String groupids = rs.getString("groupid");
                studentg.addItem(groupids);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     private void fillcombotimeslot(){
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            String sql = "select * from timeslots";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String timeslots = rs.getString("timeslots");
                timeslot.addItem(timeslots);
                timeslot1.addItem(timeslots);
                timeslot2.addItem(timeslots);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    } 
    
      private void fillcombolocation(){
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            String sql = "select * from ro";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String rooms = rs.getString("Room");
                locationcombo.addItem(rooms);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    } 
    
       private void fillcombolecturer(){
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            String sql = "select * from lecturers";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String lecturer = rs.getString("lecturername");
                lecturer2.addItem(lecturer);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    } 
     
     
     private void fillcombosubjects(){
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            String sql = "select * from subjects";
            pst = con.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while(rs.next()){
                String subject = rs.getString("subject");
                subjecta.addItem(subject);
                subjectb.addItem(subject);
                subjectc.addItem(subject);
                subjectd.addItem(subject);
                subjecte.addItem(subject);
                subjectf.addItem(subject);
                subject1.addItem(subject);
                subject2.addItem(subject);
                subject3.addItem(subject);
                subject4.addItem(subject);
                subject5.addItem(subject);
                subject6.addItem(subject);
                subject7.addItem(subject);
                subject8.addItem(subject);
                subject9.addItem(subject);
                subject10.addItem(subject);
                subject11.addItem(subject);
                subject12.addItem(subject);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
     
     
     private void table_update_lecturers()
         {
             int p;
              try {
            
       
        
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            pst = con.prepareStatement("select * from lectureractivesession");
           
           
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            p = Rss.getColumnCount();
            
            DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
            dft.setRowCount(0);
            
               while(rs.next())
               {
                   Vector v2 = new Vector();
                   
                   for(int q=1; q<=p; q++)
                   {
                       v2.add(rs.getString("id"));
                       v2.add(rs.getString("lecturer"));
                       v2.add(rs.getString("timeslot"));
                       v2.add(rs.getString("monday"));
                       v2.add(rs.getString("tuesday"));
                       v2.add(rs.getString("wednesday"));
                       v2.add(rs.getString("thursday"));
                       v2.add(rs.getString("friday"));
                       v2.add(rs.getString("saturday"));
                       
                   }
                   
                   dft.addRow(v2);
               }
               
            
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            
            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
    
    
    
    private void table_update_students()
         {
             int p;
              try {
            
       
        
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            pst = con.prepareStatement("select * from studentactivesession");
           
           
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            p = Rss.getColumnCount();
            
            DefaultTableModel dft = (DefaultTableModel) jTable2.getModel();
            dft.setRowCount(0);
            
               while(rs.next())
               {
                   Vector v2 = new Vector();
                   
                   for(int q=1; q<=p; q++)
                   {
                       v2.add(rs.getString("id"));
                       v2.add(rs.getString("studentgroup"));
                       v2.add(rs.getString("timeslot"));
                       v2.add(rs.getString("monday"));
                       v2.add(rs.getString("tuesday"));
                       v2.add(rs.getString("wednesday"));
                       v2.add(rs.getString("thursday"));
                       v2.add(rs.getString("friday"));
                       v2.add(rs.getString("saturday"));
                       
                   }
                   
                   dft.addRow(v2);
               }
               
            
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            
            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
    
    private void table_update_location()
         {
             int p;
              try {
            
       
        
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            pst = con.prepareStatement("select * from locationactivesessions");
           
           
            ResultSet rs = pst.executeQuery();
            ResultSetMetaData Rss = rs.getMetaData();
            p = Rss.getColumnCount();
            
            DefaultTableModel dft = (DefaultTableModel) jTable3.getModel();
            dft.setRowCount(0);
            
               while(rs.next())
               {
                   Vector v2 = new Vector();
                   
                   for(int q=1; q<=p; q++)
                   {
                       v2.add(rs.getString("id"));
                       v2.add(rs.getString("location"));
                       v2.add(rs.getString("timeslot"));
                       v2.add(rs.getString("monday"));
                       v2.add(rs.getString("tuesday"));
                       v2.add(rs.getString("wednesday"));
                       v2.add(rs.getString("thursday"));
                       v2.add(rs.getString("friday"));
                       v2.add(rs.getString("saturday"));
                       
                   }
                   
                   dft.addRow(v2);
               }
               
            
        } catch (ClassNotFoundException ex) {
            
            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {
            
            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
         }
   
    
    
    
    
    
    private void clearbutton_cs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutton_cs1ActionPerformed
      
    }//GEN-LAST:event_clearbutton_cs1ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int r = jTable1.getSelectedRow();
        String id = jTable1.getValueAt(r, 0).toString();
        String  lec = jTable1.getValueAt(r, 1).toString();
        String  time  = jTable1.getValueAt(r, 2).toString();
        String  mon  = jTable1.getValueAt(r, 3).toString();
        String  tue = jTable1.getValueAt(r, 4).toString();
        String  wed  = jTable1.getValueAt(r, 5).toString();
        String  thu  = jTable1.getValueAt(r, 6).toString();
        String  fri  = jTable1.getValueAt(r, 7).toString();
        String  sat  = jTable1.getValueAt(r, 8).toString();
        
          lecturer2.setSelectedItem(lec);
          timeslot.setSelectedItem(time);
          subjecta.setSelectedItem(mon);
          subjectb.setSelectedItem(tue);
          subjectc.setSelectedItem(wed);
          subjectd.setSelectedItem(thu);
          subjecte.setSelectedItem(fri);
          subjectf.setSelectedItem(sat);
          
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void timeslotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeslotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeslotActionPerformed

    private void lecturer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lecturer2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lecturer2ActionPerformed

    private void subjectaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectaActionPerformed

    private void subjectbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectbActionPerformed

    private void subjectcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectcActionPerformed

    private void subjectdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectdActionPerformed

    private void subjecteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjecteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjecteActionPerformed

    private void subjectfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectfActionPerformed

    private void studentgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentgActionPerformed

    private void timeslot1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeslot1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeslot1ActionPerformed

    private void subject3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject3ActionPerformed

    private void subject2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject2ActionPerformed

    private void subject1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject1ActionPerformed

    private void subject6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject6ActionPerformed

    private void subject5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject5ActionPerformed

    private void subject4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject4ActionPerformed

    private void locationcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_locationcomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_locationcomboActionPerformed

    private void timeslot2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeslot2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeslot2ActionPerformed

    private void subject9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject9ActionPerformed

    private void subject8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject8ActionPerformed

    private void subject7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject7ActionPerformed

    private void subject12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject12ActionPerformed

    private void subject11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject11ActionPerformed

    private void subject10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subject10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subject10ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        DefaultTableModel dft = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();
        String ActiveSessions = null;

        studentg.setSelectedItem(dft.getValueAt(selectedIndex, 1).toString());
        timeslot1.setSelectedItem(dft.getValueAt(selectedIndex, 2).toString());
        subject1.setSelectedItem(dft.getValueAt(selectedIndex, 3).toString());
        subject2.setSelectedItem(dft.getValueAt(selectedIndex, 4).toString());
        subject3.setSelectedItem(dft.getValueAt(selectedIndex, 5).toString());
        subject4.setSelectedItem(dft.getValueAt(selectedIndex, 6).toString());
        subject5.setSelectedItem(dft.getValueAt(selectedIndex, 7).toString());
        subject6.setSelectedItem(dft.getValueAt(selectedIndex, 8).toString());
      
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTable3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable3MouseClicked
        DefaultTableModel dft = (DefaultTableModel) jTable3.getModel();
        int selectedIndex = jTable3.getSelectedRow();
        String ActiveSessions = null;

        locationcombo.setSelectedItem(dft.getValueAt(selectedIndex, 1).toString());
        timeslot2.setSelectedItem(dft.getValueAt(selectedIndex, 2).toString());
        subject7.setSelectedItem(dft.getValueAt(selectedIndex, 3).toString());
        subject8.setSelectedItem(dft.getValueAt(selectedIndex, 4).toString());
        subject9.setSelectedItem(dft.getValueAt(selectedIndex, 5).toString());
        subject10.setSelectedItem(dft.getValueAt(selectedIndex, 6).toString());
        subject11.setSelectedItem(dft.getValueAt(selectedIndex, 7).toString());
        subject12.setSelectedItem(dft.getValueAt(selectedIndex, 8).toString());
    }//GEN-LAST:event_jTable3MouseClicked

    private void savestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savestudentActionPerformed
     
        String studentgroup = studentg.getSelectedItem().toString();
        String timeslot = timeslot1.getSelectedItem().toString();
        String monday = subject1.getSelectedItem().toString();
        String tuesday = subject2.getSelectedItem().toString();
        String wednesday = subject3.getSelectedItem().toString();
        String thursday = subject4.getSelectedItem().toString();
        String friday = subject5.getSelectedItem().toString();
        String saturday = subject6.getSelectedItem().toString();

        Connection con;
        PreparedStatement insert;

        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            insert = con.prepareStatement("insert into studentactivesession(studentgroup,timeslot,monday,tuesday,wednesday,thursday,friday,saturday)values(?,?,?,?,?,?,?,?)");

            insert.setString(1, studentgroup);
            insert.setString(2, timeslot);
            insert.setString(3, monday);
            insert.setString(4, tuesday);
            insert.setString(5, wednesday);
            insert.setString(6, thursday);
            insert.setString(7, friday);
            insert.setString(8, saturday);
   
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Added");

            studentg.setSelectedIndex(0);
            timeslot1.setSelectedIndex(0);
            subject1.setSelectedIndex(0);
            subject2.setSelectedIndex(0);
            subject3.setSelectedIndex(0);
            subject4.setSelectedIndex(0);
            subject5.setSelectedIndex(0);
            subject6.setSelectedIndex(0);
            
            
         
            table_update_students();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_savestudentActionPerformed

    private void updatestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatestudentActionPerformed
        DefaultTableModel dft = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow();

        try {

        int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());
        String studentgroup = studentg.getSelectedItem().toString();
        String timeslot = timeslot1.getSelectedItem().toString();
        String monday = subject1.getSelectedItem().toString();
        String tuesday = subject2.getSelectedItem().toString();
        String wednesday = subject3.getSelectedItem().toString();
        String thursday = subject4.getSelectedItem().toString();
        String friday = subject5.getSelectedItem().toString();
        String saturday = subject6.getSelectedItem().toString();

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            pst = con.prepareStatement("update studentactivesession set studentgroup=?,timeslot=?,monday=?,tuesday=?,wednesday=?,thursday=?,friday=?,saturday=? where id=? ");

            pst.setString(1, studentgroup);
            pst.setString(2, timeslot);
            pst.setString(3, monday);
            pst.setString(4, tuesday);
            pst.setString(5, wednesday);
            pst.setString(6, thursday);
            pst.setString(7, friday);
            pst.setString(8, saturday);
            pst.setInt(9, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Updated");

            studentg.setSelectedIndex(0);
            timeslot1.setSelectedIndex(0);
            subject1.setSelectedIndex(0);
            subject2.setSelectedIndex(0);
            subject3.setSelectedIndex(0);
            subject4.setSelectedIndex(0);
            subject5.setSelectedIndex(0);
            subject6.setSelectedIndex(0);
            
            table_update_students();
         
           

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatestudentActionPerformed

    private void deletestudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletestudentActionPerformed
       DefaultTableModel dft = (DefaultTableModel) jTable2.getModel();
        int selectedIndex = jTable2.getSelectedRow(); 

        try {

            int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());

            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure?","Warning",JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
                pst = con.prepareStatement("delete from studentactivesession where id=?");

                pst.setInt(1, id);

            }

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Deleted");
            table_update_students();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_deletestudentActionPerformed

    private void savelocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savelocationActionPerformed
        
        String location = locationcombo.getSelectedItem().toString();
        String timeslot = timeslot2.getSelectedItem().toString();
        String monday = subject7.getSelectedItem().toString();
        String tuesday = subject8.getSelectedItem().toString();
        String wednesday = subject9.getSelectedItem().toString();
        String thursday = subject10.getSelectedItem().toString();
        String friday = subject11.getSelectedItem().toString();
        String saturday = subject12.getSelectedItem().toString();

        Connection con;
        PreparedStatement insert;

        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            insert = con.prepareStatement("insert into locationactivesessions(location,timeslot,monday,tuesday,wednesday,thursday,friday,saturday)values(?,?,?,?,?,?,?,?)");

            insert.setString(1, location);
            insert.setString(2, timeslot);
            insert.setString(3, monday);
            insert.setString(4, tuesday);
            insert.setString(5, wednesday);
            insert.setString(6, thursday);
            insert.setString(7, friday);
            insert.setString(8, saturday);
   
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Added");

            locationcombo.setSelectedIndex(0);
            timeslot2.setSelectedIndex(0);
            subject7.setSelectedIndex(0);
            subject8.setSelectedIndex(0);
            subject9.setSelectedIndex(0);
            subject10.setSelectedIndex(0);
            subject11.setSelectedIndex(0);
            subject12.setSelectedIndex(0);
            
            
         
            table_update_location();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_savelocationActionPerformed

    private void updatelocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatelocationActionPerformed
        DefaultTableModel dft = (DefaultTableModel) jTable3.getModel();
        int selectedIndex = jTable3.getSelectedRow();

        try {

        int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());
        String location = locationcombo.getSelectedItem().toString();
        String timeslot = timeslot2.getSelectedItem().toString();
        String monday = subject7.getSelectedItem().toString();
        String tuesday = subject8.getSelectedItem().toString();
        String wednesday = subject9.getSelectedItem().toString();
        String thursday = subject10.getSelectedItem().toString();
        String friday = subject11.getSelectedItem().toString();
        String saturday = subject12.getSelectedItem().toString();

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            pst = con.prepareStatement("update locationactivesessions set location=?,timeslot=?,monday=?,tuesday=?,wednesday=?,thursday=?,friday=?,saturday=? where id=? ");

            pst.setString(1, location);
            pst.setString(2, timeslot);
            pst.setString(3, monday);
            pst.setString(4, tuesday);
            pst.setString(5, wednesday);
            pst.setString(6, thursday);
            pst.setString(7, friday);
            pst.setString(8, saturday);
            pst.setInt(9, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Updated");

            studentg.setSelectedIndex(0);
            timeslot2.setSelectedIndex(0);
            subject7.setSelectedIndex(0);
            subject8.setSelectedIndex(0);
            subject9.setSelectedIndex(0);
            subject10.setSelectedIndex(0);
            subject11.setSelectedIndex(0);
            subject12.setSelectedIndex(0);
            
            
         
            table_update_location();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatelocationActionPerformed

    private void deletelocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelocationActionPerformed
       DefaultTableModel dft = (DefaultTableModel) jTable3.getModel();
        int selectedIndex = jTable3.getSelectedRow(); 

        try {

            int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());

            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure?","Warning",JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
                pst = con.prepareStatement("delete from locationactivesessions where id=?");

                pst.setInt(1, id);

            }

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Deleted");
            table_update_location();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deletelocationActionPerformed

    private void savelecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savelecturerActionPerformed
   
        String studentgroup = lecturer2.getSelectedItem().toString();
        String timeslot1 = timeslot.getSelectedItem().toString();
        String monday = subjecta.getSelectedItem().toString();
        String tuesday = subjectb.getSelectedItem().toString();
        String wednesday = subjectc.getSelectedItem().toString();
        String thursday = subjectd.getSelectedItem().toString();
        String friday = subjecte.getSelectedItem().toString();
        String saturday = subjectf.getSelectedItem().toString();

        Connection con;
        PreparedStatement insert;

        try {

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            insert = con.prepareStatement("INSERT INTO lectureractivesession (lecturer,timeslot,monday,tuesday,wednesday,thursday,friday,saturday) values(?,?,?,?,?,?,?,?)");

            insert.setString(1, studentgroup);
            insert.setString(2, timeslot1);
            insert.setString(3, monday);
            insert.setString(4, tuesday);
            insert.setString(5, wednesday);
            insert.setString(6, thursday);
            insert.setString(7, friday);
            insert.setString(8, saturday);
   
            insert.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Added");

            lecturer2.setSelectedIndex(0);
            timeslot.setSelectedIndex(0);
            subjecta.setSelectedIndex(0);
            subjectb.setSelectedIndex(0);
            subjectc.setSelectedIndex(0);
            subjectd.setSelectedIndex(0);
            subjecte.setSelectedIndex(0);
            subjectf.setSelectedIndex(0);
            
            
         
            table_update_lecturers();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_savelecturerActionPerformed

    private void updatelecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatelecturerActionPerformed
      DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
      int selectedIndex = jTable1.getSelectedRow();

        try {

        int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());
        String lecturer = lecturer2.getSelectedItem().toString();
        String timeslot1 = timeslot.getSelectedItem().toString();
        String monday = subjecta.getSelectedItem().toString();
        String tuesday = subjectb.getSelectedItem().toString();
        String wednesday = subjectc.getSelectedItem().toString();
        String thursday = subjectd.getSelectedItem().toString();
        String friday = subjecte.getSelectedItem().toString();
        String saturday = subjectf.getSelectedItem().toString();

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
            pst = con.prepareStatement("update lectureractivesession set lecturer=?,timeslot=?,monday=?,tuesday=?,wednesday=?,thursday=?,friday=?,saturday=? where id=? ");

            pst.setString(1, lecturer);
            pst.setString(2, timeslot1);
            pst.setString(3, monday);
            pst.setString(4, tuesday);
            pst.setString(5, wednesday);
            pst.setString(6, thursday);
            pst.setString(7, friday);
            pst.setString(8, saturday);
            pst.setInt(9, id);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Updated");

            studentg.setSelectedIndex(0);
            timeslot.setSelectedIndex(0);
            subject1.setSelectedIndex(0);
            subject2.setSelectedIndex(0);
            subject3.setSelectedIndex(0);
            subject4.setSelectedIndex(0);
            subject5.setSelectedIndex(0);
            subject6.setSelectedIndex(0);
            
            
         
            table_update_lecturers();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updatelecturerActionPerformed

    private void deletelecturerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletelecturerActionPerformed
       DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
        int selectedIndex = jTable1.getSelectedRow(); 

        try {

            int id = Integer.parseInt(dft.getValueAt(selectedIndex, 0).toString());

            int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure?","Warning",JOptionPane.YES_NO_OPTION);

            if(dialogResult == JOptionPane.YES_OPTION)
            {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/timetable","root","");
                pst = con.prepareStatement("delete from lectureractivesession where id=?");

                pst.setInt(1, id);

            }

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this,"Successfully Deleted");
            table_update_lecturers();

        } catch (ClassNotFoundException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
        catch (SQLException ex) {

            Logger.getLogger(ReviseActiveSessions.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_deletelecturerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReviseActiveSessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReviseActiveSessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReviseActiveSessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReviseActiveSessions.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReviseActiveSessions().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Lecturer;
    private javax.swing.JButton clearbutton_cs1;
    private javax.swing.JButton deletelecturer;
    private javax.swing.JButton deletelocation;
    private javax.swing.JButton deletestudent;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JComboBox<String> lecturer2;
    private javax.swing.JComboBox<String> locationcombo;
    private javax.swing.JButton savelecturer;
    private javax.swing.JButton savelocation;
    private javax.swing.JButton savestudent;
    private javax.swing.JComboBox<String> studentg;
    private javax.swing.JComboBox<String> subject1;
    private javax.swing.JComboBox<String> subject10;
    private javax.swing.JComboBox<String> subject11;
    private javax.swing.JComboBox<String> subject12;
    private javax.swing.JComboBox<String> subject2;
    private javax.swing.JComboBox<String> subject3;
    private javax.swing.JComboBox<String> subject4;
    private javax.swing.JComboBox<String> subject5;
    private javax.swing.JComboBox<String> subject6;
    private javax.swing.JComboBox<String> subject7;
    private javax.swing.JComboBox<String> subject8;
    private javax.swing.JComboBox<String> subject9;
    private javax.swing.JComboBox<String> subjecta;
    private javax.swing.JComboBox<String> subjectb;
    private javax.swing.JComboBox<String> subjectc;
    private javax.swing.JComboBox<String> subjectd;
    private javax.swing.JComboBox<String> subjecte;
    private javax.swing.JComboBox<String> subjectf;
    private javax.swing.JComboBox<String> timeslot;
    private javax.swing.JComboBox<String> timeslot1;
    private javax.swing.JComboBox<String> timeslot2;
    private javax.swing.JButton updatelecturer;
    private javax.swing.JButton updatelocation;
    private javax.swing.JButton updatestudent;
    // End of variables declaration//GEN-END:variables
}
