/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package timetablemanagement;

/**
 *
 * @author Bimsara De Silva
 */
public class SessionsDashboard extends javax.swing.JFrame {

    /**
     * Creates new form SessionsDashboard
     */
    public SessionsDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SystemLecturer1 = new javax.swing.JButton();
        SystemLecturer2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        clearbutton_cs1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SystemLecturer1.setBackground(new java.awt.Color(0, 102, 255));
        SystemLecturer1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemLecturer1.setText("Consecutive, Parallel and Non Overlapping Sessions");
        SystemLecturer1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SystemLecturer1.setContentAreaFilled(false);
        SystemLecturer1.setOpaque(true);
        SystemLecturer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemLecturer1ActionPerformed(evt);
            }
        });

        SystemLecturer2.setBackground(new java.awt.Color(0, 153, 51));
        SystemLecturer2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SystemLecturer2.setText("Active Sessions");
        SystemLecturer2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SystemLecturer2.setContentAreaFilled(false);
        SystemLecturer2.setOpaque(true);
        SystemLecturer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystemLecturer2ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(204, 204, 204));
        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Sessions Dashboard");
        jLabel7.setOpaque(true);

        clearbutton_cs1.setBackground(new java.awt.Color(153, 153, 153));
        clearbutton_cs1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clearbutton_cs1.setText("Back To Main Dashboard");
        clearbutton_cs1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        clearbutton_cs1.setContentAreaFilled(false);
        clearbutton_cs1.setOpaque(true);
        clearbutton_cs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearbutton_cs1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearbutton_cs1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(SystemLecturer1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SystemLecturer2, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(clearbutton_cs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 39, Short.MAX_VALUE)
                .addComponent(SystemLecturer2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SystemLecturer1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SystemLecturer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemLecturer1ActionPerformed
        dispose();
        Sessions ses = new Sessions();
        ses.setVisible(true);
    }//GEN-LAST:event_SystemLecturer1ActionPerformed

    private void SystemLecturer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystemLecturer2ActionPerformed
        dispose();
        ActiveSessions sess = new ActiveSessions();
        sess.setVisible(true);
    }//GEN-LAST:event_SystemLecturer2ActionPerformed

    private void clearbutton_cs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearbutton_cs1ActionPerformed
        dispose();
        MainDashboard md = new MainDashboard();
        md.setVisible(true);    
    }//GEN-LAST:event_clearbutton_cs1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SessionsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SessionsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SessionsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SessionsDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SessionsDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SystemLecturer1;
    private javax.swing.JButton SystemLecturer2;
    private javax.swing.JButton clearbutton_cs1;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
